### ISSUE TITLE
Fix Logo 

### ISSUE THREAD

**Issue by INam1995** [anki2003ta/Museum#13]
![image](https://github.com/user-attachments/assets/de5eed69-1a3a-4c4a-9f24-9261f10acbaf)
I can fix the logo and its name as shown in the screenshot. I also want to clarify: do you want "Explore" to be a navbar item, or is "Explore" the website name? Please assign this issue to me under the gssoc-ext label.

**Comment by saimohan11** [comment]
@anki2003ta please assign this task

**Comment by INam1995** [comment]
@anki2003ta 
But I’ve been actively working on this issue and already made considerable progress. I’ll be submitting my PR shortly.

**Comment by INam1995** [comment]
Hi @anki2003ta,
I noticed that I was previously assigned to this issue, and I've been actively working on it. Could you kindly clarify how another contributor is submitting a pull request for the same issue?

**Comment by INam1995** [comment]
Hey @anki2003ta 
I am facing an issue with MongoDB while trying to run the project on your localhost. Please update the project or let me know if I need to configure the MongoDB connection myself. Kindly consider this issue.

**Comment by rishyym0927** [comment]
@anki2003ta  can you assign this issue to me also?
