### ISSUE TITLE
Returning Complete User Data on Console.log 

### ISSUE THREAD

**Issue by rishyym0927** [anki2003ta/Museum#16]
![image](https://github.com/user-attachments/assets/aca4c733-a70a-4a90-9995-a13a9d504383)

Hey whenever the user register themselves on your website , their salt and hash get completely logged which is a major issue and caause security concerns.

**Comment by anki2003ta** [comment]
How it is arises problem..explain. in brief?

**Comment by rishyym0927** [comment]
though the hashed password itself might not be directly usable, exposing it in logs or returning it in API responses increases the attack surface. If an attacker gains access to the logs or responses, they can attempt to reverse-engineer or brute-force the hashed password.Although the salt is designed to make it harder to crack passwords, exposing it alongside the hash could aid an attacker in trying to brute-force or launch dictionary attacks using precomputed tables (like rainbow tables). If the salt is available, it defeats part of its purpose, which is to protect against such attacks.

Console logs can be accessed by developers, operations personnel, and potentially others with access to server logs or browser developer tools. By logging sensitive data like hashed passwords and salts, you're increasing the risk that an attacker or an unauthorized person may access this information.

Principle of Least Privilege: This principle states that users or systems should only have access to the data they absolutely need. A user or client should never need access to their own hashed password or salt.

**Comment by anki2003ta** [comment]
Ok then 👌

**Comment by rishyym0927** [comment]
please add the gssoc labels

**Comment by anki2003ta** [comment]
Added
