### ISSUE TITLE
Adding logo

### ISSUE THREAD

**Issue by shreyad2806** [anki2003ta/Museum#2]
I can make a personlised LOGOfor your website.
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by rishyym0927** [comment]
Please I also wanna work on this issue assign it to me as well

**Comment by anki2003ta** [comment]
Can you please send video the change you have made

**Comment by anki2003ta** [comment]
So that I can close this issue

**Comment by shreyad2806** [comment]
YOU HAVE MERGED MY PR BUT NOT ASSIGNED LABELS SO ITS NOT SHOWING IN MY GSSOC LEADERBOARD
PLEASE ADD LABELS OF GSSOC AND HACKTOBERFEST
