### ISSUE TITLE
Set Up Dockerfile for Node.js Project

### ISSUE THREAD

**Issue by rishyym0927** [anki2003ta/Museum#26]
We need to create and configure a Dockerfile to containerize the Node.js project. This will allow us to build and deploy the application in a consistent environment. The Dockerfile should support environment variables and expose the necessary ports for the application.

**Comment by anki2003ta** [comment]
Ok

**Comment by rishyym0927** [comment]
I guess this is not a level 1 issue , can you upgrade it ?

**Comment by rishyym0927** [comment]
please review it

**Comment by rishyym0927** [comment]
please mark its label and give it level 3
