### ISSUE TITLE
No Validations For Signup Email & Password

### ISSUE THREAD

**Issue by ParasY1724** [anki2003ta/Museum#3]
**Description:**
User can signup even after entering invalid email address or short password _eg) email : p12 , password : 00_

**Issue Video:**

https://github.com/user-attachments/assets/c111236f-03a5-4647-a60e-b7199f6a4bd3

**Comment by ParasY1724** [comment]
Please Assign this task to me under gssoc-extd24

**Comment by saimohan11** [comment]
Assign me this task Please add Gssoc-ext tag

**Comment by lomash-choudhary** [comment]
@anki2003ta please assign this to me under gssoc-ext

**Comment by anki2003ta** [comment]
Ok

**Comment by anki2003ta** [comment]
> Assign me this task Please add Gssoc-ext tag

Done

**Comment by saimohan11** [comment]
Thank you @anki2003ta
