### ISSUE TITLE
Can any contributor  make a route in show.ejs file before edit route for chatbot payment 

### ISSUE THREAD

**Issue by anki2003ta** [anki2003ta/Museum#54]
![WhatsApp Image 2024-10-05 at 2 12 01 PM](https://github.com/user-attachments/assets/961181bd-a066-4621-bdbb-67b7548bf975)

**Comment by anki2003ta** [comment]
![WhatsApp Image 2024-10-05 at 2 18 19 PM](https://github.com/user-attachments/assets/20ec82da-13f8-414e-8f9e-cc95dec5af8a)
instead of attaching a link by making seperate render for payment part ,you can make a seperate route for that

**Comment by ifeelsam** [comment]
can you explain a bit more

**Comment by ifeelsam** [comment]
???
